name: Scrape latest data tets

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6-56/5 * * * *'

# for pushing
permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Enable caching and define a custom cache key suffix
      id: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Check python version
      run: python --version
    - name: Run a command
      run: echo "Code was pushed to ${{ github.ref }}"
    - name: Fetch data
      run: uv run main.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
